#!/usr/bin/env node
/* ============================================================================
   dibby universe landing — static pre-render build.

   WHY: the pages localize via client-side JS (i18n). AI crawlers (GPTBot,
   PerplexityBot, ClaudeBot, …) and most non-Google engines do NOT run JS, so
   this script "bakes" one static HTML file per (page × language) with the text,
   store badges, screenshots and JSON-LD already in the markup.

   STRUCTURE (data-driven from landing/games.config.js):
     /                 → universe hub        (hub.html)
     /<locale>/        → universe hub
     /<slug>/          → a game page         (game.html), e.g. /dibby/, /dash/
     /<locale>/<slug>/ → a game page
   plus legal/utility pages, sitemap, robots, llms.txt, manifest, favicon, 404.

   USAGE:  node build.cjs        → writes ./dist/ (deploy that folder)
   ========================================================================== */
"use strict";

const fs = require("fs");
const path = require("path");

// ---- config ---------------------------------------------------------------
const SITE_URL = "https://dibbyplay.com"; // canonical site (no trailing slash). dib.by 301s here
const ROOT = __dirname;
const SRC = path.join(ROOT, "landing");
const ASSETS_SRC = path.join(ROOT, "assets");
const OUT = path.join(ROOT, "dist");

// Load the data tables exactly like the browser does.
global.window = {};
require(path.join(SRC, "i18n.js"));        // LANGS, FRIEND_SLUGS, FRIEND_NAMES, I18N
require(path.join(SRC, "i18n.games.js"));  // HUB, GAME_COPY (authored EN + RU)
// Machine-translated locales (the other 17) for HUB/GAME_COPY/EXTRA, generated by
// the translation workflow. Optional: build still runs (en/ru only) if it's absent.
if (fs.existsSync(path.join(SRC, "i18n.games.more.js"))) require(path.join(SRC, "i18n.games.more.js"));
require(path.join(SRC, "games.config.js")); // GAMES, STORES_BY_LANG, GAME_BY_SLUG
const { LANGS, FRIEND_SLUGS, FRIEND_NAMES, I18N, HUB, GAME_COPY, GAMES, STORES_BY_LANG } = global.window;

const PAGE_GAMES = GAMES.filter(g => g.page); // games that get their own page

// ---- publisher / legal (unchanged) ----------------------------------------
const PUBLISHER = {
  name:    "Malashenkov Anton",
  email:   "support@dib.by",
  address: "",
  phone:   "",
  updated: "2026-06-23"
};
const YANDEX_PRIVACY = "https://yandex.com/legal/confidential/";
const SAMEAS = [
  "https://t.me/dibbyplay_bot",
  "https://www.rustore.ru/catalog/app/com.xopoiii.dibby"
];
const LEGAL_SLUGS = ["privacy", "support", "legal"];
const LEGAL_DIR = path.join(SRC, "legal");

const LEGAL = {};
for (const f of fs.readdirSync(LEGAL_DIR)) {
  if (!f.endsWith(".json")) continue;
  LEGAL[f.slice(0, -5)] = JSON.parse(fs.readFileSync(path.join(LEGAL_DIR, f), "utf8"));
}
const LEGAL_LANGS = LANGS.map(l => l.code).filter(c => LEGAL[c]);

// merge each locale's footer + cookie labels into I18N so the baked chrome is localized
for (const code of LEGAL_LANGS) {
  const extra = Object.assign({}, LEGAL[code].footer, LEGAL[code].cookie);
  for (const k in extra) if (I18N[code] && I18N[code][k] == null) I18N[code][k] = extra[k];
}

// per-language: URL sub-path, hreflang/lang code, writing system class, og locale
const URLCODE = { en: "", ru: "ru", zh_CN: "zh-cn", zh_TW: "zh-tw", ja: "ja", ko: "ko", de: "de", fr: "fr", es: "es", pt: "pt", pl: "pl", uk: "uk", it: "it", id: "id", tr: "tr", vi: "vi", th: "th", hi: "hi", ar: "ar" };
const HREFLANG = { en: "en", ru: "ru", zh_CN: "zh-Hans", zh_TW: "zh-Hant", ja: "ja", ko: "ko", de: "de", fr: "fr", es: "es", pt: "pt", pl: "pl", uk: "uk", it: "it", id: "id", tr: "tr", vi: "vi", th: "th", hi: "hi", ar: "ar" };
const SCRIPT_OF = { ja: "ja", zh_CN: "cjk", zh_TW: "cjk", ko: "cjk", th: "thai", hi: "deva", ar: "arab" };
const RTL = { ar: true };
const OGLOCALE = { en: "en_US", ru: "ru_RU", zh_CN: "zh_CN", zh_TW: "zh_TW", ja: "ja_JP", ko: "ko_KR", de: "de_DE", fr: "fr_FR", es: "es_ES", pt: "pt_PT", pl: "pl_PL", uk: "uk_UA", it: "it_IT", id: "id_ID", tr: "tr_TR", vi: "vi_VN", th: "th_TH", hi: "hi_IN", ar: "ar_SA" };

// schema.org Offer.availability, derived from the game's release status so the
// structured data never overstates: live games are InStock; in-moderation ("soon")
// and in-dev games are PreOrder (the closest valid schema.org value to "coming soon").
const AVAILABILITY = { live: "https://schema.org/InStock", soon: "https://schema.org/PreOrder", dev: "https://schema.org/PreOrder" };

const REVEAL = ["pushok", "kvaki", "kotik", "utenok", "zaychik", "zvyozdochka"];
const CONFETTI = ["pushok", "kvaki", "kotik", "utenok", "zaychik", "zvyozdochka"];
const FAQ_PAIRS = [["q5", "a5"], ["q1", "a1"], ["q2", "a2"], ["q3", "a3"], ["q4", "a4"]];

// Build-local chrome strings the i18n.js table doesn't carry (en + ru; other
// locales fall back to en). Keep disjoint from I18N keys.
const EXTRA = {
  en: { navAllGames: "All games", aboutKicker: "In short", factPrice: "Price", factPlatforms: "Platforms", factGenre: "Genre", factControls: "Controls", factFriends: "Friends to rescue", factLangs: "Languages", factStatus: "Status" },
  ru: { navAllGames: "Все игры", aboutKicker: "Если коротко", factPrice: "Цена", factPlatforms: "Платформы", factGenre: "Жанр", factControls: "Управление", factFriends: "Спасти друзей", factLangs: "Языки", factStatus: "Статус" }
};
// merge the other 17 locales' chrome labels from the generated translations file
for (const c in (global.window.EXTRA_MORE || {})) EXTRA[c] = global.window.EXTRA_MORE[c];

// Monochrome store glyphs. Must stay byte-identical to game.html / hub.html.
const STORE_SVG = {
  ios:     '<svg viewBox="0 0 24 24"><path d="M16.4 12.7c0-2.2 1.8-3.3 1.9-3.4-1-1.5-2.6-1.7-3.2-1.7-1.4-.1-2.6.8-3.3.8-.7 0-1.7-.8-2.8-.8-1.5 0-2.8.8-3.5 2.1-1.5 2.6-.4 6.5 1.1 8.6.7 1 1.5 2.2 2.6 2.1 1-.04 1.4-.7 2.7-.7s1.6.7 2.7.66c1.1-.02 1.8-1 2.5-2a9 9 0 001.1-2.3c-.02-.01-2.1-.8-2.1-3.2zM14.3 6.1c.6-.7 1-1.7.9-2.7-.8.03-1.9.5-2.5 1.3-.5.6-1 1.6-.9 2.6.9.07 1.8-.5 2.5-1.2z"/></svg>',
  android: '<svg viewBox="0 0 24 24"><path d="M3.6 2.3c-.2.2-.3.5-.3.9v17.6c0 .4.1.7.3.9l.1.1L13.5 12 3.7 2.2l-.1.1zM17 8.3l-2.4-1.4L5.6 16l9-5.2L17 9.4v-1.1zM4.7 21.3l9.9-9.3 2.4 1.4c.9.5.9 1.4 0 1.9l-2.4 1.4-9.9 4.6zM5.6 8L14.6 17 17 15.6c.9-.5.9-1.4 0-1.9L14.6 12 5.6 8z"/></svg>',
  rustore: '<svg viewBox="0 0 24 24"><path d="M8 7V6a4 4 0 018 0v1h2.4l.9 12.6a1.4 1.4 0 01-1.4 1.4H6.1a1.4 1.4 0 01-1.4-1.4L5.6 7H8zm2 0h4V6a2 2 0 00-4 0v1zm-2 3a1 1 0 100 2 1 1 0 000-2zm8 0a1 1 0 100 2 1 1 0 000-2z"/></svg>',
  yandex:  '<svg viewBox="0 0 24 24"><path d="M7 7h10a4 4 0 014 4v4.2A2.8 2.8 0 0116.4 17l-1.2-1.5H8.8L7.6 17A2.8 2.8 0 013 15.2V11a4 4 0 014-4zm-.2 3v1.3H5.5v1.4h1.3V14h1.4v-1.3h1.3v-1.4H8.2V10H6.8zM15 10.6a1 1 0 100 2.1 1 1 0 000-2.1zm2.3 2.1a1 1 0 100 2 1 1 0 000-2z"/></svg>',
  vk:      '<svg viewBox="0 0 24 24"><path d="M12.9 16.4c-5.6 0-8.9-3.9-9-10.4h2.8c.1 4.8 2.2 6.8 3.9 7.2V6h2.6v4.1c1.7-.2 3.4-2.1 4-4.1h2.6c-.5 2.5-2.4 4.4-3.6 5.1 1.2.6 3.4 2.3 4.2 5.3h-2.9c-.6-2-2.2-3.5-4.3-3.7v3.7h-.3z"/></svg>',
  telegram:'<svg viewBox="0 0 24 24"><path d="M21.9 4.3l-3 14.1c-.2 1-.8 1.2-1.7.8l-4.6-3.4-2.2 2.1c-.3.3-.5.5-1 .5l.3-4.8L18.4 6c.4-.3-.1-.5-.6-.2L7.4 12.5l-4.5-1.4c-1-.3-1-1 .2-1.5l17.6-6.8c.8-.3 1.5.2 1.2 1.5z"/></svg>'
};

// ---- helpers ---------------------------------------------------------------
let CSS_MIN = "";
function minifyCss(s) {
  return s.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\s+/g, " ").replace(/\s*([{}:;,>])\s*/g, "$1").replace(/;}/g, "}").trim();
}
const escText = s => String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const escAttr = s => escText(s).replace(/"/g, "&quot;");
const jsStr = o => JSON.stringify(o);

// paths
const hubPath  = code => (code === "en" ? "/" : `/${URLCODE[code]}/`);
const gamePath = (slug, code) => (code === "en" ? "" : `/${URLCODE[code]}`) + `/${slug}/`;
const absUrl   = p => SITE_URL + p;
// asset/site prefix by directory depth (number of path segments before the file)
const prefixForDepth = depth => depth === 0 ? "" : Array(depth + 1).join("../");

// merged strings for a page: chrome (I18N + EXTRA) + page copy (HUB or a game).
function mergedT(kind, code) {
  const layers = [I18N.en, code !== "en" ? I18N[code] : null, EXTRA.en, code !== "en" ? EXTRA[code] : null];
  if (kind === "__hub__") layers.push(HUB.en, code !== "en" ? HUB[code] : null);
  else { const gc = GAME_COPY[kind] || {}; layers.push(gc.en, code !== "en" ? gc[code] : null); }
  const t = {};
  for (const l of layers) if (l) for (const k in l) if (l[k] != null) t[k] = l[k];
  return t;
}

function storeMeta(t) {
  return {
    ios:     { pre: "ios",     small: t.downloadOn, big: t.appstore },
    android: { pre: "android", small: t.getItOn,    big: t.playstore },
    rustore: { pre: "rustore", small: t.getItOn,    big: t.rustore },
    yandex:  { pre: "yandex",  small: t.playOn,     big: t.yandexgames },
    vk:      { pre: "vk",      small: t.playOn,     big: t.vkminigames },
    telegram:{ pre: "telegram",small: t.playOn || t.getItOn, big: "Telegram" }
  };
}
const storesFor = code => STORES_BY_LANG[code] || ["ios", "android"];
const liveOf = (game, k) => (game.liveStores && game.liveStores[k] && game.liveStores[k].status === "live" && game.liveStores[k].href) ? game.liveStores[k] : null;
const extAttr = url => url && url !== "#get" ? ' target="_blank" rel="noopener"' : "";

function storeBadges(game, t, code) {
  const meta = storeMeta(t);
  return storesFor(code).map(k => {
    const m = meta[k];
    const live = liveOf(game, k);
    const href = live ? live.href : "#get";
    const soon = live ? "" : '<span class="store__soon">' + escText(t.soon) + "</span>";
    return '<a class="store" href="' + escAttr(href) + '"' + extAttr(href) + ' data-prereg="' + m.pre + '">' + soon + STORE_SVG[k] +
      '<span class="store__txt"><span class="store__small">' + escText(m.small) + '</span><span class="store__big">' + escText(m.big) + "</span></span></a>";
  }).join("");
}
function footerGetLinks(game, t, code) {
  const meta = storeMeta(t);
  return storesFor(code).map(k => {
    const live = liveOf(game, k);
    const href = live ? live.href : "#get";
    return '<a href="' + escAttr(href) + '"' + extAttr(href) + ' data-prereg="' + meta[k].pre + '">' + escText(meta[k].big) + "</a>";
  }).join("");
}

function friendsGrid(names, assetPrefix) {
  const revealedIdx = REVEAL.map(s => FRIEND_SLUGS.indexOf(s)).filter(i => i >= 0);
  const isRevealed = {};
  revealedIdx.forEach(i => { isRevealed[i] = true; });
  const order = revealedIdx.concat(FRIEND_SLUGS.map((_, i) => i).filter(i => !isRevealed[i]));
  return order.map(i => {
    const found = !!isRevealed[i];
    const no = String(i + 1).padStart(2, "0");
    const name = names[i];
    return '<div class="friend ' + (found ? "friend--found" : "friend--locked") + '">' +
      '<div class="friend__pic"><img class="pixelated" src="' + assetPrefix + "friends/" + FRIEND_SLUGS[i] + '.png" alt="' + (found ? escAttr(name) : "") + '" /></div>' +
      '<div class="friend__name">' + (found ? escText(name) : "???") + "</div>" +
      '<div class="friend__no">#' + no + "</div></div>";
  }).join("");
}

function faqList(t) {
  return FAQ_PAIRS.map(([q, a], i) =>
    '<div class="faq-item">' +
    '<button class="faq-q" id="faq-q-' + i + '" aria-expanded="false" aria-controls="faq-a-' + i + '">' + escText(t[q]) + '<span class="chev" aria-hidden="true">+</span></button>' +
    '<div class="faq-a" id="faq-a-' + i + '" role="region" aria-labelledby="faq-q-' + i + '"><p>' + escText(t[a]) + "</p></div></div>"
  ).join("");
}

function confettiRow(assetPrefix) {
  return CONFETTI.map((s, i) =>
    '<img class="pixelated bob" style="animation-delay:' + (i * 0.3) + 's" src="' + assetPrefix + "friends/" + s + '.png" alt="" />'
  ).join("");
}

// hero phone screen (SSR/no-JS view; the client swaps in the crossfade gallery)
function heroPicture(game, t, assetPrefix) {
  const base = assetPrefix + game.hero;
  const alt = escAttr(game.fullName + " — gameplay");
  return '<picture><source type="image/webp" srcset="' + base + '.webp" /><img class="pixelated phone__poster" width="540" height="960" fetchpriority="high" src="' + base + '.png" alt="' + alt + '" /></picture>';
}

function shotsGrid(game, t, assetPrefix) {
  return game.screens.map((name, i) => {
    const base = assetPrefix + game.screenDir + name;
    const cap = t["shot" + (i + 1)] || "";
    const alt = escAttr(game.name + " — " + cap);
    return '<figure class="shot"><div class="shot__frame"><picture><source type="image/webp" srcset="' + base + '.webp" />' +
      '<img class="pixelated" loading="lazy" width="540" height="960" src="' + base + '.png" alt="' + alt + '" /></picture></div>' +
      '<figcaption>' + escText(cap) + "</figcaption></figure>";
  }).join("");
}

function keyfactsTable(game, t, code) {
  const meta = storeMeta(t);
  const platforms = storesFor(code).map(k => meta[k].big).join(", ");
  const rows = [
    [t.factPrice, t.factPriceV],
    [t.factPlatforms, platforms],
    [t.factGenre, t.factGenreV],
    [t.factControls, t.factControlsV],
    game.friends ? [t.factFriends, "36"] : null,
    [t.factLangs, "19"],
    [t.factStatus, t.factStatusV]
  ].filter(Boolean);
  return "<tbody>" + rows.map(([th, td]) =>
    '<tr><th scope="row">' + escText(th) + "</th><td>" + escText(td) + "</td></tr>"
  ).join("") + "</tbody>";
}

// universe hub: one card per game
function gameCards(t, code, assetPrefix) {
  const blurbKey = { dibby: "cardDibby", dash: "cardDash", chirp: "cardChirp", sling: "cardSling" };
  const statusLabel = { live: t.cardPlay, soon: t.cardSoon, dev: t.cardDev };
  return GAMES.map(g => {
    const icon = assetPrefix + g.icon.replace(/\.png$/, "");
    const inner =
      '<div class="gcard__icon"><picture><source type="image/webp" srcset="' + icon + '.webp" /><img class="pixelated" width="120" height="120" loading="lazy" src="' + icon + '.png" alt="' + escAttr(g.fullName) + '" /></picture></div>' +
      '<div class="gcard__body"><h3 class="gcard__name">' + escText(g.name) + "</h3>" +
      '<p class="gcard__blurb">' + escText(t[blurbKey[g.slug]] || "") + "</p>" +
      '<span class="gcard__status gcard__status--' + g.status + '">' + escText(statusLabel[g.status]) + "</span></div>";
    const style = ' style="--card-accent:' + g.accent + ";--card-accent-deep:" + g.accentDeep + '"';
    return g.page
      ? '<a class="gcard"' + style + ' href="' + gamePath(g.slug, code) + '">' + inner + "</a>"
      : '<div class="gcard gcard--soon"' + style + ">" + inner + "</div>";
  }).join("");
}
function footerCardLinks(code) {
  return GAMES.map(g => g.page
    ? '<a href="' + gamePath(g.slug, code) + '">' + escText(g.name) + "</a>"
    : '<span class="footer-dim">' + escText(g.name) + "</span>"
  ).join("");
}

function langMenuBaked(code, currentPath) {
  // currentPath(code2) → the localized URL of THIS page, so the baked links keep
  // the visitor on the same page in another language.
  return LANGS.map(l => {
    const cur = l.code === code ? ' aria-current="true"' : "";
    return '<a class="lang__opt" role="menuitem" href="' + currentPath(l.code) + '" data-code="' + l.code + '"' + cur + '>' + escText(l.name) + "</a>";
  }).join("");
}

function hreflangLinks(pathFor) {
  const links = LANGS.map(l => `<link rel="alternate" hreflang="${HREFLANG[l.code]}" href="${absUrl(pathFor(l.code))}" />`);
  links.push(`<link rel="alternate" hreflang="x-default" href="${absUrl(pathFor("en"))}" />`);
  return links.join("\n");
}

// ---- JSON-LD ---------------------------------------------------------------
const ORG = () => {
  const o = { "@type": "Organization", "@id": SITE_URL + "/#org", name: "Dibby", url: SITE_URL + "/", logo: { "@type": "ImageObject", url: SITE_URL + "/assets/icon.png", width: 1024, height: 1024 } };
  if (SAMEAS.length) o.sameAs = SAMEAS;
  return o;
};
const gameId = slug => SITE_URL + "/" + slug + "/#game";

function gameNode(game, code, t) {
  const node = {
    "@type": ["VideoGame", "MobileApplication"],
    "@id": gameId(game.slug),
    name: game.fullName,
    description: t.sub || t.aboutLede,
    applicationCategory: "GameApplication",
    genre: game.genre,
    operatingSystem: (game.platforms || ["iOS", "Android"]).join(", "),
    gamePlatform: game.platforms || ["iOS", "Android"],
    inLanguage: HREFLANG[code],
    url: absUrl(gamePath(game.slug, code)),
    image: SITE_URL + "/assets/" + game.hero + ".png",
    screenshot: game.screens.map(s => SITE_URL + "/assets/" + game.screenDir + s + ".png"),
    datePublished: PUBLISHER.updated,
    dateModified: PUBLISHER.updated,
    isPartOf: { "@id": SITE_URL + "/#website" },
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD", availability: AVAILABILITY[game.status] || "https://schema.org/InStock" },
    publisher: { "@id": SITE_URL + "/#org" },
    author: { "@id": SITE_URL + "/#org" }
  };
  if (SAMEAS.length) node.sameAs = SAMEAS;
  return node;
}

function jsonLdGame(game, code, t) {
  const website = { "@type": "WebSite", "@id": SITE_URL + "/#website", url: SITE_URL + "/", name: "Dibby", inLanguage: HREFLANG[code], publisher: { "@id": SITE_URL + "/#org" } };
  const graph = [ORG(), website, gameNode(game, code, t)];
  // only emit FAQ structured data when the page actually renders an FAQ section
  // (e.g. Chirp's lean page drops it) — orphan FAQPage markup is a rich-results warning.
  if (!game.sections || game.sections.indexOf("faq") !== -1) {
    graph.push({
      "@type": "FAQPage", "@id": absUrl(gamePath(game.slug, code)) + "#faq", inLanguage: HREFLANG[code], isPartOf: { "@id": SITE_URL + "/#website" },
      mainEntity: FAQ_PAIRS.map(([q, a]) => ({ "@type": "Question", name: t[q], acceptedAnswer: { "@type": "Answer", text: t[a] } }))
    });
  }
  return '<script type="application/ld+json">' + jsStr({ "@context": "https://schema.org", "@graph": graph }) + "</script>";
}

function jsonLdHub(code, t) {
  const website = { "@type": "WebSite", "@id": SITE_URL + "/#website", url: SITE_URL + "/", name: "Dibby", inLanguage: HREFLANG[code], publisher: { "@id": SITE_URL + "/#org" } };
  const list = {
    "@type": "ItemList", "@id": absUrl(hubPath(code)) + "#games", inLanguage: HREFLANG[code], name: t.universeTitle,
    itemListElement: PAGE_GAMES.map((g, i) => ({ "@type": "ListItem", position: i + 1, url: absUrl(gamePath(g.slug, code)), name: g.fullName }))
  };
  const graph = { "@context": "https://schema.org", "@graph": [ORG(), website, list] };
  return '<script type="application/ld+json">' + jsStr(graph) + "</script>";
}

// slim per-page i18n payload: only this locale + en fallback (merged for the page)
function slimI18nJs(kind, code) {
  const i18n = { en: mergedT(kind, "en") };
  const fnames = { en: FRIEND_NAMES.en };
  if (code !== "en") { i18n[code] = mergedT(kind, code); fnames[code] = FRIEND_NAMES[code] || FRIEND_NAMES.en; }
  return "window.LANGS=" + jsStr(LANGS) + ";window.FRIEND_SLUGS=" + jsStr(FRIEND_SLUGS) +
    ";window.FRIEND_NAMES=" + jsStr(fnames) + ";window.I18N=" + jsStr(i18n) + ";\n";
}

// ---- shared head/chrome rewrites -------------------------------------------
function applyHtmlTag(h, code) {
  return h.replace('<html lang="en" data-script="latin">',
    `<html lang="${HREFLANG[code]}" data-script="${SCRIPT_OF[code] || "latin"}"${RTL[code] ? ' dir="rtl"' : ""}>`);
}
function applyI18nText(h, t) {
  return h.replace(/data-i18n="(\w+)"\s*>([\s\S]*?)<\//g, (m, key) => {
    const val = t[key];
    return val == null ? m : `data-i18n="${key}">${escText(val)}</`;
  });
}
function fillTokens(h, map) {
  for (const k in map) h = h.split("{{" + k + "}}").join(map[k]);
  return h;
}
function finishHead(h, code, headExtra, assetPrefix) {
  // og:locale, inline CSS, relative asset depth, hreflang + JSON-LD
  h = h.replace('<meta property="og:locale" content="en_US" />', `<meta property="og:locale" content="${OGLOCALE[code]}" />`);
  h = h.replace('<link rel="stylesheet" href="styles.css" />', "<style>" + CSS_MIN + "</style>");
  h = h.split("../assets/").join(assetPrefix + "assets/");
  h = h.replace("</head>", headExtra + "\n</head>");
  return h;
}
function localizeLegalFooter(h, code) {
  if (code !== "en" && LEGAL[code]) {
    const pre = "/" + URLCODE[code];
    h = h.split('href="/privacy/"').join('href="' + pre + '/privacy/"');
    h = h.split('href="/support/"').join('href="' + pre + '/support/"');
    h = h.split('href="/legal/"').join('href="' + pre + '/legal/"');
  }
  return h;
}

// ---- render a game page ----------------------------------------------------
function renderGame(game, code, template) {
  const t = mergedT(game.slug, code);
  const names = FRIEND_NAMES[code] || FRIEND_NAMES.en;
  const depth = code === "en" ? 1 : 2;          // /dibby/ or /ru/dibby/
  const assetPrefix = prefixForDepth(depth);     // "../" or "../../"
  // Baked containers use the template baseline ("../assets/"); finishHead()
  // rewrites every "../assets/" to the right depth in one pass.
  const ap = "../assets/";
  const title = game.fullName + " — " + t.kicker;
  const desc = (t.sub || t.aboutLede) + " " + (t.footerSoon || "");
  const canonical = absUrl(gamePath(game.slug, code));

  let h = template;
  h = applyHtmlTag(h, code);
  h = fillTokens(h, {
    TITLE: escAttr(title), DESC: escAttr(desc.trim()), ACCENT: game.accent, ACCENT_DEEP: game.accentDeep,
    CANONICAL: canonical, OG_ALT: escAttr(title), GAME_NAME: escText(game.name),
    HUB_PATH: hubPath(code), PRELOAD_HERO: ap + game.hero + ".webp"
  });
  h = applyI18nText(h, t);

  // baked dynamic containers — hero phone (or, for a teaser with no gameplay yet,
  // the app icon centred as a splash, with no client-side crossfade)
  if (game.teaser) {
    const ic = ap + game.icon.replace(/\.png$/, "");
    const splash = '<picture><source type="image/webp" srcset="' + ic + '.webp" /><img class="pixelated teaser-splash" width="240" height="240" fetchpriority="high" src="' + ic + '.png" alt="' + escAttr(game.fullName) + '" /></picture>';
    h = h.replace('<div class="phone__screen" data-phone></div>', '<div class="phone__screen">' + splash + "</div>");
  } else {
    h = h.replace('<div class="phone__screen" data-phone></div>', '<div class="phone__screen" data-phone>' + heroPicture(game, t, ap) + "</div>");
  }
  h = h.replace('<div class="shots-grid" data-shots></div>', '<div class="shots-grid" data-shots>' + shotsGrid(game, t, ap) + "</div>");
  h = h.replace('<table class="keyfacts" data-keyfacts></table>', '<table class="keyfacts" data-keyfacts>' + keyfactsTable(game, t, code) + "</table>");
  h = h.split('<div class="stores" data-stores></div>').join('<div class="stores" data-stores>' + storeBadges(game, t, code) + "</div>");
  h = h.split('<div data-getlinks><a href="#get" data-prereg="ios">App Store</a><a href="#get" data-prereg="android">Google Play</a></div>').join('<div data-getlinks>' + footerGetLinks(game, t, code) + "</div>");
  h = h.split('<div class="confetti-row" data-confetti></div>').join('<div class="confetti-row" data-confetti>' + confettiRow(ap) + "</div>");
  h = h.replace('<div class="final-confetti" data-confetti2></div>', '<div class="final-confetti" data-confetti2>' + confettiRow(ap) + "</div>");

  // friends gallery — keep + bake, or strip entirely
  if (game.friends) {
    h = h.replace('<div class="friends-grid" data-friends></div>', '<div class="friends-grid" data-friends>' + friendsGrid(names, ap) + "</div>");
  } else {
    h = h.replace(/<!--FRIENDS:START-->[\s\S]*?<!--FRIENDS:END-->/g, "");
    h = h.replace(/<a [^>]*data-friends-link[^>]*>[\s\S]*?<\/a>\s*/g, "");
  }

  // optional sections (data-driven via game.sections): keep only the listed ones,
  // strip the rest by their <!--SEC:x-->…<!--/SEC:x--> markers + any nav/footer
  // anchors pointing at them. Lets Chirp go lean and Dash add a runner-only Modes.
  const OPTIONAL_SECS = ["how", "why", "faq", "modes", "shots"];
  const secs = game.sections || OPTIONAL_SECS;
  OPTIONAL_SECS.forEach(s => {
    if (secs.indexOf(s) === -1) {
      h = h.replace(new RegExp("<!--SEC:" + s + "-->[\\s\\S]*?<!--/SEC:" + s + "-->", "g"), "");
      h = h.replace(new RegExp('<a [^>]*href="#' + s + '"[^>]*>[\\s\\S]*?<\\/a>\\s*', "g"), "");
    }
  });

  // primary CTA destination
  const live = game.cta ? liveOf(game, game.cta) : null;
  if (live) h = h.split('href="#get" data-cta').join('href="' + escAttr(live.href) + '" target="_blank" rel="noopener" data-cta');

  // language picker (baked) — links stay on this game in each locale
  const pathFor = c => gamePath(game.slug, c);
  h = h.replace('<div class="lang__menu" id="langMenu" role="menu"></div>', '<div class="lang__menu" id="langMenu" role="menu">' + langMenuBaked(code, pathFor) + "</div>");
  const _langName = (LANGS.find(l => l.code === code) || { name: "English" }).name;
  h = h.replace('<span id="langCurrent">English</span>', '<span id="langCurrent">' + escText(_langName) + "</span>");
  // accessible name must contain the visible language name (WCAG 2.2 "label in name")
  h = h.replace('aria-label="Language"', 'aria-label="' + escAttr(_langName + " · " + (t.langLabel || "Language")) + '"');

  // injected config + slim i18n
  const paths = {}; LANGS.forEach(l => { paths[l.code] = pathFor(l.code); });
  const gameClient = {
    slug: game.slug, cta: game.cta, friends: !!game.friends, liveStores: game.liveStores || {},
    screens: game.screens.map(s => ({ webp: ap + game.screenDir + s + ".webp", png: ap + game.screenDir + s + ".png" })),
    gameplay: game.gameplay ? { mp4: ap + game.gameplay.mp4, poster: ap + game.gameplay.poster + ".webp" } : null
  };
  const cfg = "<script>window.DIBBY_LANG=" + jsStr(code) + ";window.DIBBY_PATHS=" + jsStr(paths) +
    ";window.STORES_BY_LANG=" + jsStr(STORES_BY_LANG) + ";window.DIBBY_GAME=" + jsStr(gameClient) + ";</script>";
  h = h.replace('<script src="i18n.js"></script>', cfg + '\n<script src="i18n.js"></script>');

  h = finishHead(h, code, hreflangLinks(pathFor) + "\n" + jsonLdGame(game, code, t), assetPrefix);
  h = localizeLegalFooter(h, code);
  return h;
}

// ---- render the universe hub ----------------------------------------------
function renderHub(code, template) {
  const t = mergedT("__hub__", code);
  const names = FRIEND_NAMES[code] || FRIEND_NAMES.en;
  const depth = code === "en" ? 0 : 1;
  const assetPrefix = prefixForDepth(depth);
  const ap = "../assets/"; // template baseline; finishHead() normalizes depth
  const title = t.metaTitle;
  const desc = t.metaDesc;
  const canonical = absUrl(hubPath(code));

  let h = template;
  h = applyHtmlTag(h, code);
  h = fillTokens(h, {
    TITLE: escAttr(title), DESC: escAttr(desc), ACCENT: "#bde8db", ACCENT_DEEP: "#9ed7c4",
    CANONICAL: canonical, OG_ALT: escAttr(title), DIBBY_PATH: gamePath("dibby", code)
  });
  h = applyI18nText(h, t);

  h = h.replace('<div class="games-grid" data-cards></div>', '<div class="games-grid" data-cards>' + gameCards(t, code, ap) + "</div>");
  h = h.replace('<div data-cardlinks></div>', '<div data-cardlinks>' + footerCardLinks(code) + "</div>");
  h = h.replace('<div class="friends-grid" data-friends></div>', '<div class="friends-grid" data-friends>' + friendsGrid(names, ap) + "</div>");
  h = h.split('<div class="confetti-row" data-confetti></div>').join('<div class="confetti-row" data-confetti>' + confettiRow(ap) + "</div>");
  h = h.replace('<div class="final-confetti" data-confetti2></div>', '<div class="final-confetti" data-confetti2>' + confettiRow(ap) + "</div>");

  const pathFor = c => hubPath(c);
  h = h.replace('<div class="lang__menu" id="langMenu" role="menu"></div>', '<div class="lang__menu" id="langMenu" role="menu">' + langMenuBaked(code, pathFor) + "</div>");
  const _langName = (LANGS.find(l => l.code === code) || { name: "English" }).name;
  h = h.replace('<span id="langCurrent">English</span>', '<span id="langCurrent">' + escText(_langName) + "</span>");
  // accessible name must contain the visible language name (WCAG 2.2 "label in name")
  h = h.replace('aria-label="Language"', 'aria-label="' + escAttr(_langName + " · " + (t.langLabel || "Language")) + '"');

  const paths = {}; LANGS.forEach(l => { paths[l.code] = pathFor(l.code); });
  const cfg = "<script>window.DIBBY_LANG=" + jsStr(code) + ";window.DIBBY_PATHS=" + jsStr(paths) + ";</script>";
  h = h.replace('<script src="i18n.js"></script>', cfg + '\n<script src="i18n.js"></script>');

  h = finishHead(h, code, hreflangLinks(pathFor) + "\n" + jsonLdHub(code, t), assetPrefix);
  h = localizeLegalFooter(h, code);
  return h;
}

// ---- legal pages (privacy / support / legal) — root-absolute paths ---------
const legalUrl = (slug, code) => SITE_URL + (code === "en" ? "/" : "/" + URLCODE[code] + "/") + slug + "/";
function fillLegalTokens(str, code) {
  const privacyUrl = (code === "en" ? "/" : "/" + URLCODE[code] + "/") + "privacy/";
  if (!PUBLISHER.address) {
    str = str.replace(/\s*\{\{PUBLISHER_ADDRESS\}\}<br>/g, "");
    str = str.replace(/[,،、，]?\s*\{\{PUBLISHER_ADDRESS\}\}/g, "");
  }
  if (!PUBLISHER.phone) {
    str = str.replace(/<br>\s*[^<\n]*\{\{PUBLISHER_PHONE\}\}/g, "");
    str = str.replace(/\{\{PUBLISHER_PHONE\}\}/g, "");
  }
  return str
    .split("{{PUBLISHER_NAME}}").join(escText(PUBLISHER.name))
    .split("{{PUBLISHER_EMAIL}}").join(escText(PUBLISHER.email))
    .split("{{PUBLISHER_ADDRESS}}").join(escText(PUBLISHER.address))
    .split("{{PUBLISHER_PHONE}}").join(escText(PUBLISHER.phone))
    .split("{{YANDEX_PRIVACY}}").join(YANDEX_PRIVACY)
    .split("{{PRIVACY_URL}}").join(privacyUrl)
    .split("{{UPDATED}}").join(escText(PUBLISHER.updated));
}
function renderLegalPage(code, slug) {
  const data = LEGAL[code];
  const page = data[slug];
  const home = code === "en" ? "/" : "/" + URLCODE[code] + "/";
  const lp = sub => home + sub + "/";
  const navLabel = s => escText(data[s].title);
  const updated = page.updated ? `<p class="legal-updated">${escText(fillLegalTokens(page.updated, code))}</p>` : "";
  const plain = s => String(s).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  const metaDesc = escAttr(plain(fillLegalTokens(page.html, code)).slice(0, 155));
  const hreflang = LEGAL_LANGS.map(c => `<link rel="alternate" hreflang="${HREFLANG[c]}" href="${legalUrl(slug, c)}" />`).join("\n") +
    `\n<link rel="alternate" hreflang="x-default" href="${legalUrl(slug, "en")}" />`;
  const breadcrumb = jsStr({
    "@context": "https://schema.org", "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Dibby", item: SITE_URL + home },
      { "@type": "ListItem", position: 2, name: page.title, item: SITE_URL + lp(slug) }
    ]
  });
  return `<!DOCTYPE html>
<html lang="${HREFLANG[code]}" data-script="${SCRIPT_OF[code] || "latin"}"${RTL[code] ? ' dir="rtl"' : ""}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>${escText(page.title)} — dibby</title>
<meta name="description" content="${metaDesc}" />
<meta name="theme-color" content="#bde8db" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32.png" />
<link rel="apple-touch-icon" href="/assets/icon.png" />
<link rel="manifest" href="/site.webmanifest" />
<link rel="canonical" href="${SITE_URL}${lp(slug)}" />
<meta name="robots" content="index,follow" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="dibby" />
<meta property="og:locale" content="${OGLOCALE[code]}" />
<meta property="og:title" content="${escAttr(page.title)} — dibby" />
<meta property="og:description" content="${metaDesc}" />
<meta property="og:url" content="${SITE_URL}${lp(slug)}" />
<meta property="og:image" content="${SITE_URL}/assets/og.png" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image" content="${SITE_URL}/assets/og.png" />
${hreflang}
<script type="application/ld+json">${breadcrumb}</script>
<link rel="stylesheet" href="/styles.css" />
</head>
<body>
<header class="site-header">
  <div class="wrap">
    <a class="logo" href="${home}" aria-label="dibby">dibby</a>
    <nav class="nav" aria-label="Legal">
      <a href="${lp("privacy")}">${navLabel("privacy")}</a>
      <a href="${lp("support")}">${navLabel("support")}</a>
      <a href="${lp("legal")}">${navLabel("legal")}</a>
    </nav>
  </div>
</header>
<main class="legal-main">
  <div class="wrap legal">
    <h1 class="section-title">${escText(page.title)}</h1>
    ${updated}
    ${fillLegalTokens(page.html, code).trim()}
    <p class="legal-back"><a href="${home}">${escText(data.back)}</a></p>
  </div>
</main>
<footer class="site-footer">
  <div class="wrap">
    <div class="footer-bottom">
      <p class="footer-made">${escText(PUBLISHER.name)}</p>
      <nav class="footer-links" aria-label="Legal">
        <a href="${lp("privacy")}">${navLabel("privacy")}</a>
        <a href="${lp("support")}">${navLabel("support")}</a>
        <a href="${lp("legal")}">${navLabel("legal")}</a>
      </nav>
    </div>
  </div>
</footer>
</body>
</html>
`;
}

// ---- 404 -------------------------------------------------------------------
function render404() {
  return `<!DOCTYPE html>
<html lang="en" data-script="latin">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>Page not found — dibby</title>
<meta name="theme-color" content="#bde8db" />
<meta name="robots" content="noindex, follow" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32.png" />
<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png" />
<link rel="stylesheet" href="/styles.css" />
</head>
<body>
<header class="site-header"><div class="wrap"><a class="logo" href="/" aria-label="dibby">dibby</a></div></header>
<main class="legal-main">
  <div class="wrap legal center">
    <h1 class="section-title">This rope didn't reach</h1>
    <p class="section-lede">The page you were looking for isn't here. Let's get you back to solid ground.</p>
    <p><a class="btn btn--lg" href="/">Back home</a></p>
  </div>
</main>
<footer class="site-footer"><div class="wrap"><div class="footer-bottom"><p class="footer-made">${escText(PUBLISHER.name)}</p></div></div></footer>
</body>
</html>
`;
}

// ---- sitemap / robots / llms / manifest / favicon --------------------------
function sitemap() {
  const entry = (loc, altPairs) => {
    const alts = altPairs.map(([hl, href]) => `    <xhtml:link rel="alternate" hreflang="${hl}" href="${href}" />`).join("\n");
    return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${PUBLISHER.updated}</lastmod>\n${alts}\n  </url>`;
  };
  const urls = [];
  // hub locales
  const hubAlts = LANGS.map(a => [HREFLANG[a.code], absUrl(hubPath(a.code))]).concat([["x-default", absUrl(hubPath("en"))]]);
  LANGS.forEach(l => urls.push(entry(absUrl(hubPath(l.code)), hubAlts)));
  // each game × locale
  PAGE_GAMES.forEach(g => {
    const alts = LANGS.map(a => [HREFLANG[a.code], absUrl(gamePath(g.slug, a.code))]).concat([["x-default", absUrl(gamePath(g.slug, "en"))]]);
    LANGS.forEach(l => urls.push(entry(absUrl(gamePath(g.slug, l.code)), alts)));
  });
  // legal pages
  LEGAL_SLUGS.forEach(slug => {
    const alts = LEGAL_LANGS.map(c => [HREFLANG[c], legalUrl(slug, c)]).concat([["x-default", legalUrl(slug, "en")]]);
    LEGAL_LANGS.forEach(c => urls.push(entry(legalUrl(slug, c), alts)));
  });
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${urls.join("\n")}\n</urlset>\n`;
}

function robots() {
  const NAMED = [
    "Googlebot", "Bingbot", "DuckDuckBot", "YandexBot", "Applebot",
    "GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "Claude-SearchBot", "anthropic-ai",
    "PerplexityBot", "Perplexity-User", "Google-Extended", "Applebot-Extended", "Meta-ExternalAgent", "Amazonbot"
  ];
  const blocks = NAMED.map(ua => `User-agent: ${ua}\nAllow: /\n`).join("\n");
  return `User-agent: *\nAllow: /\n\n${blocks}\nSitemap: ${SITE_URL}/sitemap.xml\n`;
}

function faviconSvg() {
  return `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <rect width="100" height="100" rx="22" fill="#bde8db"/>
  <line x1="50" y1="18" x2="50" y2="56" stroke="#9a6a3c" stroke-width="4" stroke-linecap="round"/>
  <circle cx="50" cy="64" r="13" fill="#f0b878" stroke="#3d4a52" stroke-width="3"/>
  <circle cx="45" cy="63" r="2.4" fill="#3d4a52"/>
  <circle cx="55" cy="63" r="2.4" fill="#3d4a52"/>
</svg>
`;
}

function webmanifest() {
  return JSON.stringify({
    name: "Dibby", short_name: "Dibby",
    description: "A cozy world of one-finger pixel games.",
    start_url: "/", display: "standalone", background_color: "#bde8db", theme_color: "#bde8db",
    icons: [
      { src: "/assets/favicon-32.png", sizes: "32x32", type: "image/png" },
      { src: "/assets/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
      { src: "/assets/icon.png", sizes: "1024x1024", type: "image/png", purpose: "any maskable" }
    ]
  }, null, 2) + "\n";
}

function llms() {
  const lines = PAGE_GAMES.map(g => {
    const t = mergedT(g.slug, "en");
    return `- [${g.fullName}](${SITE_URL}${gamePath(g.slug, "en")}): ${t.sub || t.aboutLede}`;
  }).join("\n");
  return `# Dibby\n\n> Dibby is a cozy world of free, one-finger pixel games. The flagship, Dibby (Rope Rescue), is playable now in Telegram and on RuStore for Android; Dibby Dash (a cozy runner) and Dibby Chirp (a one-tap flyer) are coming soon to the App Store and Google Play. Every game shares one soft pixel world and one warm goal — reach a little friend and bring them home.\n\n## Games\n${lines}\n\n## Pages\n- [Home](${SITE_URL}/): the Dibby world and all the games.\n- [Privacy Policy](${SITE_URL}/privacy/) · [Support](${SITE_URL}/support/) · [Legal](${SITE_URL}/legal/)\n`;
}

// ---- fs helpers ------------------------------------------------------------
function rmrf(p) { if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true }); }
function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    if (e.name === ".DS_Store") continue;
    if (e.name.endsWith(".ttf")) continue;
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (e.isDirectory()) copyDir(s, d); else fs.copyFileSync(s, d);
  }
}
function writePage(dirParts, html, kind, code) {
  const dir = path.join(OUT, ...dirParts);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html);
  fs.writeFileSync(path.join(dir, "i18n.js"), slimI18nJs(kind, code));
}

// ---- build -----------------------------------------------------------------
function build() {
  const hubTpl = fs.readFileSync(path.join(SRC, "hub.html"), "utf8");
  const gameTpl = fs.readFileSync(path.join(SRC, "game.html"), "utf8");
  rmrf(OUT);
  fs.mkdirSync(OUT, { recursive: true });

  copyDir(ASSETS_SRC, path.join(OUT, "assets"));
  CSS_MIN = minifyCss(fs.readFileSync(path.join(SRC, "styles.css"), "utf8"));
  fs.writeFileSync(path.join(OUT, "styles.css"), CSS_MIN);

  // hub: / and /<locale>/
  for (const l of LANGS) {
    const dirParts = l.code === "en" ? [] : [URLCODE[l.code]];
    writePage(dirParts, renderHub(l.code, hubTpl), "__hub__", l.code);
  }
  // game pages: /<slug>/ and /<locale>/<slug>/
  for (const g of PAGE_GAMES) {
    for (const l of LANGS) {
      const dirParts = l.code === "en" ? [g.slug] : [URLCODE[l.code], g.slug];
      writePage(dirParts, renderGame(g, l.code, gameTpl), g.slug, l.code);
    }
  }

  // legal/utility pages
  for (const code of LEGAL_LANGS) {
    for (const slug of LEGAL_SLUGS) {
      const dir = code === "en" ? path.join(OUT, slug) : path.join(OUT, URLCODE[code], slug);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "index.html"), renderLegalPage(code, slug));
    }
  }

  fs.writeFileSync(path.join(OUT, "404.html"), render404());
  fs.writeFileSync(path.join(OUT, "favicon.svg"), faviconSvg());
  fs.writeFileSync(path.join(OUT, "site.webmanifest"), webmanifest());
  fs.writeFileSync(path.join(OUT, "sitemap.xml"), sitemap());
  fs.writeFileSync(path.join(OUT, "robots.txt"), robots());
  fs.writeFileSync(path.join(OUT, "llms.txt"), llms());

  for (const f of ["app-ads.txt", "ads.txt"]) {
    const src = path.join(SRC, f);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(OUT, f));
  }

  const pages = LANGS.length * (1 + PAGE_GAMES.length);
  console.log(`Built ${pages} pages: hub + ${PAGE_GAMES.length} games (${PAGE_GAMES.map(g => g.slug).join(", ")}) × ${LANGS.length} locales → ${path.relative(ROOT, OUT)}/`);
  console.log(`Legal: ${LEGAL_SLUGS.join(", ")} × ${LEGAL_LANGS.length} locales`);
  if (JSON.stringify(PUBLISHER).includes("[")) console.log("⚠  PUBLISHER still has [placeholders].");
}

build();
